{
 "title": "Unified-Gpkg-Merger",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values({app=\"MergerService\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Batch Initialization Time  ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(batch_initialization_time_sum{app=\"MergerService\"}[$interval])) / sum(rate(batch_initialization_time_count{app=\"MergerService\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(batch_initialization_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(batch_initialization_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Total Tiles Currently Processed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tiles_in_batch{app=\"MergerService\"})"
    }
   ]
  },
  {
   "title": "Build Sources List Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(build_sources_list_time_sum{app=\"MergerService\"}[$interval])) / sum(rate(build_sources_list_time_count{app=\"MergerService\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(build_sources_list_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(build_sources_list_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Batch Work Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(batch_work_time_sum{app=\"MergerService\"}[$interval])) / sum(rate(batch_work_time_count{app=\"MergerService\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(batch_work_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(batch_work_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Task Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(task_execution_time_sum{app=\"MergerService\"}[$interval])) / sum(rate(task_execution_time_count{app=\"MergerService\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(task_execution_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(task_execution_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Merge Time Per Tile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(merge_time_per_tile_sum{app=\"MergerService\"}[$interval])) / \nsum(rate(merge_time_per_tile_count{app=\"MergerService\"}[$interval]))\n",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(merge_time_per_tile_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(merge_time_per_tile_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Upscale Time Per Tile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(upscale_time_per_tile_sum{app=\"MergerService\"}[$interval])) / sum(rate(upscale_time_per_tile_count{app=\"MergerService\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(upscale_time_per_tile_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(upscale_time_per_tile_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Total Fetch Time Per Tile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(total_fetch_time_per_tile_sum{app=\"MergerService\"}[$interval])) / sum(rate(total_fetch_time_per_tile_count{app=\"MergerService\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(total_fetch_time_per_tile_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(total_fetch_time_per_tile_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Tiles Upload Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(batch_upload_time_sum{app=\"MergerService\"}[$interval])) / sum(rate(batch_upload_time_count{app=\"MergerService\"}[$interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(batch_upload_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(batch_upload_time_bucket{app=\"MergerService\"}[$interval])))",
     "legendFormat": "p90"
    }
   ]
  }
 ]
}