{{- $chartName := include "gpkg-merger.name" . -}}
{{- $tracingUrl := include "gpkg-merger.tracingUrl" . -}}
{{- $metricsUrl := include "gpkg-merger.metricsUrl" . -}}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  GENERAL__validate: {{ .Values.env.general.validate | quote }}
  GENERAL__outputPath: {{ .Values.env.general.outputPath | quote }}
  TASK__overseerUrl: {{ .Values.rasterCommon.serviceUrls.discreteOverseer | quote }} 
  TASK__jobManagerUrl: {{ .Values.rasterCommon.serviceUrls.jobManager | quote }} 
  TASK__types: {{ .Values.env.TASK.types | quote }}
  TASK__pollingTime: {{ .Values.env.TASK.pollingTime | quote }}
  TASK__maxAttempts: {{ .Values.env.TASK.maxAttempts | quote }}
  S3__url: {{ .Values.rasterCommon.storage.s3.endpointUrl | quote }}
  S3__bucket: {{ .Values.rasterCommon.storage.s3.tilesBucket | quote }}
  Logging__LogLevel__Default: {{ .Values.env.logging.logLevel.default | quote }}
  Logging__Microsoft.AspNetCore: {{ .Values.env.logging.logLevel.aspNetCore | quote }}
  {{ if .Values.env.tracing.enabled }}
  TRACING__enabled: 'true'
  TRACING__url: {{ $tracingUrl }}
  TRACING__ratio: {{ .Values.env.tracing.ratio }} 
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  METRICS__enabled: 'true'
  METRICS__url: {{ $metricsUrl }}
  METRICS__interval: {{ .Values.env.metrics.interval }}
  {{ end }}
{{- end -}}
