{{- $chartName := include "gpkg-merger.name" . -}}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  GENERAL__validate: {{ .Values.env.general.validate | quote }}
  GENERAL__jobManagerUrl: {{ .Values.rasterCommon.serviceUrls.jobManager | quote }}
  TASK__types__taskType: {{ .Values.env.taskType | quote }}
  TASK__types__jobType: {{ .Values.env.jobType | quote }}
  TASK__pollingTime: {{ .Values.env.pollingTime | quote }}
  S3__url: {{ .Values.rasterCommon.storage.s3.endpointUrl | quote }}
  S3__bucket: {{ .Values.rasterCommon.storage.s3.tilesBucket | quote }}
  Logging__LogLevel__Default: {{ .Values.env.logging.logLevel.default | quote }}
  Logging__Microsoft.AspNetCore: {{ .Values.env.logging.logLevel.aspNetCore | quote }}
{{- end -}}
