{{- $chartName := include "gpkg-merger.name" . -}}
{{- $tracingUrl := include "gpkg-merger.tracingUrl" . -}}
{{- $metricsUrl := include "gpkg-merger.metricsUrl" . -}}
{{- $s3HttpProtocol := ternary "https://" "http://" .Values.rasterCommon.storage.s3.sslEnabled -}}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  GENERAL__validate: {{ .Values.env.general.validate | quote }}
  GENERAL__defaultConnectionLimit: {{ .Values.env.general.defaultConnectionLimit | quote }}
  TASK__jobManagerUrl: {{ .Values.rasterCommon.serviceUrls.jobManager | quote }}
  {{- range $i, $e := .Values.env.TASK.types }}
  TASK__types__{{ $i }}__jobType: {{ $e.jobType }}
  TASK__types__{{ $i }}__taskType: {{ $e.taskType }}
  {{- end }}
  TASK__pollingTime: {{ .Values.env.TASK.pollingTime | quote }}
  TASK__maxAttempts: {{ .Values.env.TASK.maxAttempts | quote }}
  S3__url: {{ printf "%s%s" $s3HttpProtocol .Values.rasterCommon.storage.s3.endpointUrl | quote }}
  S3__bucket: {{ .Values.rasterCommon.storage.s3.tilesBucket | quote }}
  S3__request_timeoutSec: {{ .Values.rasterCommon.storage.s3.request.timeoutSec | quote }}
  S3__request_retries: {{ .Values.rasterCommon.storage.s3.request.retries | quote }}
  S3__logToConsole: {{ .Values.rasterCommon.storage.s3.logToConsole | quote }}
  Logging__LogLevel__Default: {{ .Values.env.logging.logLevel.default | quote }}
  Logging__Microsoft.AspNetCore: {{ .Values.env.logging.logLevel.aspNetCore | quote }}
  {{ if .Values.env.tracing.enabled }}
  TRACING__enabled: 'true'
  TRACING__url: {{ $tracingUrl }}
  TRACING__ratio: {{ .Values.env.tracing.ratio | quote}}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  METRICS__enabled: 'true'
  METRICS__url: {{ $metricsUrl }}
  METRICS__interval: {{ .Values.env.metrics.interval | quote}}
  {{ end }}
  HTTP__retries: {{ .Values.env.HTTP.retries | quote }}
  HEARTBEAT__baseUrl: {{ .Values.rasterCommon.serviceUrls.heartbeatManager | quote }}
  HEARTBEAT__intervalMs: {{ .Values.env.heartbeat.intervalMs | quote }}
{{- end -}}
