{{- if .Values.local.storage.internalPvc.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.local.storage.internalPv.name }}
spec:
  storageClassName: {{ .Values.local.storage.storageClassName }}
  capacity:
    storage:  {{ .Values.local.storage.internalPv.storage }}
  accessModes:
    - {{ .Values.local.storage.accessModes }}
  hostPath:
    path: {{ .Values.local.storage.internalPv.hostPath }}
{{- end -}}
