{{- if .Values.local.storage.internalPvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rasterCommon.storage.fs.internalPvc.name }}
  labels:
    app: "internal"
    component: "internal"
    environment: "development"
spec:
  selector: 
    matchLabels: 
      app: "internal"
      component: "internal"
      environment: "development"
  storageClassName: host-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
{{- end -}}
