{{- if .Values.local.storage.internalPvc.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.local.storage.internalPv.name }}
  labels:
    app: "internal"
    component: "internal"
    environment: "development"
spec:
  storageClassName: host-path
  capacity:
    storage:  15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.local.storage.internalPv.directory }}
{{- end -}}