#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

RUN apt-get -y update && apt-get install -y nano

WORKDIR /src
COPY ["MergerCli/MergerCli.csproj", "MergerCli/"]
COPY ["MergerLogic/MergerLogic.csproj", "MergerLogic/"]
RUN dotnet restore "MergerCli/MergerCli.csproj"
COPY . .
WORKDIR "/src/MergerCli"

RUN dotnet build "MergerCli.csproj" -c Release -o /app/build

RUN dotnet publish "MergerCli.csproj" -c Release -o /app/publish

WORKDIR /app
ENTRYPOINT ["dotnet", "MergerCli.dll"]
