global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

shtok: false
enabled: true
environment: development
nodePort: 30030 #for minikube deployment only
replicaCount: 1
initialDelaySeconds: 60
resetOnConfigChange: true
isExporter: false

cloudProvider:
  dockerRegistryUrl: 'acrarolibotnonprod.azurecr.io'
  imagePullSecretName: 'acr-registry'
  flavor: openshift

image:
  repository: tiles-merger-service
  tag: 'metrics'

local:
  s3:
    secret:
      create: false
      accessKeyId: minikube
      secretAccessKey: minikube
  storage:
    internalPv:
      create: false #for local deployment only
      name: local-tiles-pv
      storage: 5Gi
      hostPath: '/tiles' #tiles hostPatch
    ingestionPv:
      create: false #for local deployment only
      name: local-sources-pv
      storage: 5Gi
      hostPath: /layerSources
    internalPvc:
      create: false #for local deployment only
      storage: 4Gi
    ingestionSourcePvc:
      create: false #for local deployment only
      storage: 4Gi
    accessModes: ReadWriteOnce
    storageClassName: host-path

rasterCommon:
  useNodeAffinity: false
  serviceUrls:
    jobManager: "http://job-manager-raster-dev-job-manager"
    heartbeatManager: "http://heartbeat-manager-raster-dev-heartbeat-manager"
  storage:
    fs:
      ingestionSourcePvc:
        enabled: true
        name: local-sources-pvc
        subPath: ingestion-source
      internalPvc:
        name: internal-pvc-nfs
        tilesSubPath: tiles
        gpkgSubPath: config
    s3:
      endpointUrl: "10.8.0.9:9000"
      tilesBucket: raster-dev
      secretName: "raster-dev-s3-secret"
      sslEnabled: false
      request:
        timeoutSec: 5
        retries: 3
      logToConsole: false
  ca:
    secretName: ''
    path: '/usr/local/share/ca-certificates'
    key: 'ca.crt'
env:
  port: 80
  targetPort: 8080
  protocol: TCP
  general:
    validate: false
    batchSize: 1000
  TASK:
    types:
      - jobType: 'Ingestion_Update'
        taskType: 'tilesMerging'
      - jobType: 'Ingestion_New'
        taskType: 'tilesMerging'
    pollingTime: 1000
    maxAttempts: 3
  heartbeat:
    intervalMs: 300
  HTTP:
    retries: 2
  logging:
    logLevel:
      default: "Information"
      aspNetCore: "Warning"
  tracing:
    enabled: false
    url: http://localhost:4317/v1/trace
    ratio: 0.01
  metrics:
    enabled: true
    scrape: true
    port: 9185
    measurementBuckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15, 50, 250, 500]
resources:
  enabled: false
  value:
    limits:
      cpu: "3"
      memory: "3Gi"
    requests:
      cpu: "1000m"
      memory: "1280Mi"
